# Generated by Django 4.1.6 on 2023-02-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_price_alter_product_score'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_products',
            field=models.ManyToManyField(related_name='order_products', to='products.product'),
        ),
    ]
